### ISSUE TITLE
glTF assets

### ISSUE THREAD

**Issue by define-private-public** [zacharycarter/zengine#1]
Hey, I'm not sure if you read that article posted by the Godot team, but they mentioned glTF as an asset spec.  It doesn't look that bad and might be useful for zengine:

https://github.com/KhronosGroup/glTF/tree/master/specification/2.0

**Comment by zacharycarter** [comment]
Assimp may already have this feature: https://github.com/assimp/assimp/pull/697

I'm not sure if it supports 2.0 or not but I can try if I can find a sample gltf 2.0 asset

**Comment by zacharycarter** [comment]
Nevermind, it looks like it's still a WIP - https://github.com/assimp/assimp/issues/1301 - I'd rather wait till assimp supports this rather than try to implement it myself.

Either way thank you for bringing this to my attention, wasn't aware of it previously.

**Comment by define-private-public** [comment]
Might be good to close this then.  I'll leave it up to you.
