### ISSUE TITLE
Example 00 fails to build on Linux

### ISSUE THREAD

**Issue by define-private-public** [zacharycarter/zengine#4]
commit 54a37516827773afa7be9889238afdcd6887a244 is installed

Error is this:
```
/home/ben/.nimble/pkgs/zengine-0.1.1/zengine/models.nim(284, 6) Error: undeclared identifier: 'getMaterialColor'
```

**Comment by zacharycarter** [comment]
Please see - https://github.com/zacharycarter/nimassimp/commit/2aca8214abbc345622a64f88cf86b91ad3c6ed28

I think the fix would probably be to uninstall the nimassimp package from nimble, and reinstall zengine so it pulls the right version. That or you could alternatively clone my nimassimp repo and install it.

I'm not sure if fowlmouth is active or not but he has several useful repositories we may want to consider adding to zengine. Another one is his bindings to - http://www.ode.org/

**Comment by define-private-public** [comment]
Seems to be fine from the patch I posted.
